### ISSUE TITLE
PeerTube instance for livestreaming

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [MoneroSpace/defcon-cryptocurrency-village#9]
https://taiga.getmonero.org/project/michael-monero-village-at-defcon/us/3

**Comment by scottAnselmo** [comment]
"With version 3, it now possible to live stream with OBS and Jitsi Meet. Using PeerTube is a more private and decentralized alternative to YouTube.

Once saved videos are posted, the community could help seed the videos with WebTorrent.

We will need a VPS with enough bandwidth and storage to handle video streaming."

Assigned to ajs in Taiga

**Comment by scottAnselmo** [comment]
Meeting Minutes:

No copper cabled networks. Consensus to record, but not livestream since livestream will only happen maybe 25% of open vilalge time. Recordings to be uploaded within a week of the con

**Comment by SamsungGalaxyPlayer** [comment]
Closing this issue because livestream is not needed, recordings only
